name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd flashcards
          npm install

      - name: Build
        run: |
          cd flashcards
          npm run build

      - name: Create .nojekyll file
        run: |
          cd flashcards/dist
          touch .nojekyll

      - name: Verify built files
        run: |
          cd flashcards/dist
          cat index.html
          ls -la assets/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./flashcards/dist
          force_orphan: true 